### ISSUE TITLE
react-leaflet-canvas-markers as npm module

### ISSUE THREAD

**Issue by iamgbayer** [lycheelin/react-leaflet-canvas-markers#2]
Congratulations by the wrapper,

Can you publish this module on npm?

Would be cool to use it like,
```
import CanvasMarkersLayer from 'react-leaflet-canvas-marker'
```

**Comment by lycheelin** [comment]
@iamgbayer It would be cool, but It contains a link library of 'Leaflet.Canvas-Markers'
